### PR TITLE
Add development docs for Docker using dev scripts

### PR DESCRIPTION
**Pull request by seadb**
Add development docs for Docker using dev scripts
- updated README.md

### CODE REVIEW

**Comment by seadb** [comment]
I don't think this is totally right.  Seems like there is a custom Dockerfile needed for this to work?

**Comment by mtfurlan** [comment]
No, you have postgres in a docker container, and the port is exposed, and bound to your local machine, so you just have the npm server connect to it as if you have a local postgres server.

**Comment by Mierenga** [comment]
The Dockerfile for this is maintained by Docker here: https://hub.docker.com/_/postgres/. The localdb script pulls from the official repository.

Thanks for writing this up!

**Comment by seadb** [comment]
I'm familiar with the official postgres docker image.  I initially had some trouble running the app (it was saying the tables didn't exist) so I thought maybe there was a custom dockerfile you were using.  But I got it working, I think I just needed to restart the app.

**Pull request merged**
